/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admins/': RouteRecordInfo<'/admins/', '/admins', Record<never, never>, Record<never, never>>,
    '/branches/': RouteRecordInfo<'/branches/', '/branches', Record<never, never>, Record<never, never>>,
    '/cars/': RouteRecordInfo<'/cars/', '/cars', Record<never, never>, Record<never, never>>,
    '/forgot-password/': RouteRecordInfo<'/forgot-password/', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/forgot-password/[token]': RouteRecordInfo<'/forgot-password/[token]', '/forgot-password/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
  }
}
